language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer update --prefer-dist
script:
  # - php ./vendor/phpunit/phpunit/phpunit
  - php ./vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="80b65a15a783f3ca91af2635f701052e94179ebf84aad0a031dcc90dddd30394" --format=php-clover coverage.clover
notifications:
  email:
    - dev@dankempster.co.uk

branches:
  only:
    - develop
    - master
